#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Tue Sep 25 18:29:15 2012

from core.window import pick_window
from core.process import kill_process
import wx

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.CAPTION | wx.CLOSE_BOX | wx.MINIMIZE_BOX | wx.MAXIMIZE_BOX | wx.SYSTEM_MENU | wx.RESIZE_BORDER | wx.FRAME_TOOL_WINDOW | wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        self.btnKill = wx.Button(self, -1, "Select a window...")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnBtnKillClick, self.btnKill)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Window Killer")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.GridSizer(1, 1, 0, 0)
        sizer_1.Add(self.btnKill, 0, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade
        
    def OnBtnKillClick(self, event):  # wxGlade: MyFrame.<event_handler>

        process_id = pick_window()
        kill_process(process_id)
        event.Skip()

# end of class MyFrame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    myFrame = MyFrame(None, -1, "")
    app.SetTopWindow(myFrame)
    myFrame.Show()
    app.MainLoop()
