#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Tue Sep 25 18:29:15 2012

import wx
from core.module_handler import delete_module

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.CAPTION | wx.CLOSE_BOX | wx.MINIMIZE_BOX | wx.MAXIMIZE_BOX | wx.SYSTEM_MENU | wx.RESIZE_BORDER | wx.FRAME_TOOL_WINDOW | wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        self.btnKill = wx.Button(self, -1, "Select a window...")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnBtnKillClick, self.btnKill)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Window Killer")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.GridSizer(1, 1, 0, 0)
        sizer_1.Add(self.btnKill, 0, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade
        
    def OnBtnKillClick(self, event):  # wxGlade: MyFrame.<event_handler>
        import ctypes, re
        import subprocess
        from subprocess import call
        d = ctypes.CDLL('./external/xwininfo.so')
        window_id = d.getwindow_main();
        #wx.MessageBox(str(window_id), 'Window ID', wx.OK + wx.CANCEL)
        
        p = subprocess.Popen([
                              'xprop',
                              '_NET_WM_PID',
                              '-id',
                              str(window_id),
                              ], stdout=subprocess.PIPE)
        prepared_process_id = process_id = p.communicate()[0]
        reg_matches = re.match(r'_NET_WM_PID\(CARDINAL\) = (\d+)', prepared_process_id)
        if reg_matches:
            process_id = reg_matches.group(1)
            call(['kill', '-9', str(process_id)])
        else:
            wx.MessageBox('Internal error.', 'Process ID', wx.OK + wx.CANCEL)
        
        
        delete_module('ctypes')
        delete_module('re')
        delete_module('subprocess')
        event.Skip()

# end of class MyFrame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    myFrame = MyFrame(None, -1, "")
    app.SetTopWindow(myFrame)
    myFrame.Show()
    app.MainLoop()
